function [data, auxData, metaData, txtData, weights] = mydata_Astrangia_poculata
% file generated by prt_mydata

%% set metaData
metaData.phylum     = 'Cnidaria';
metaData.class      = 'Anthozoa';
metaData.order      = 'Scleractinia';
metaData.family     = 'Rhizangiidae';
metaData.species    = 'Astrangia_poculata';
metaData.species_en = 'northern star coral';

metaData.ecoCode.climate = {'Af','Am','Aw','Cfa','Dfa','Dfb'};
metaData.ecoCode.ecozone = {'MAN'};
metaData.ecoCode.habitat = {'biMp'};
metaData.ecoCode.embryo  = {'Mpf'};
metaData.ecoCode.migrate = {};
metaData.ecoCode.food    = {'biP'};
metaData.ecoCode.gender  = {'D'};
metaData.ecoCode.reprod  = {'Ob'};

metaData.T_typical  = C2K(22); % K, body temp

metaData.data_0     = {'Wdi','Wdi','Wwi','am','Wdim','tR','Wwi','ah','Ri'};
metaData.data_1     = {};

metaData.COMPLETE   = 6; % using criteria of LikaKear2011

metaData.author     = {'Caroline Fleming'};
metaData.date_subm  = [2021 5 19];
metaData.email      = {'cgflem@bu.edu'};
metaData.address    = {'Boston University'};

metaData.curator    = {'Starrlight Augustine'};
metaData.email_cur  = {'starrlight.augustine@akvaplan.niva.no'};
metaData.date_acc   = [2021 5 19];

%% set zero-variate data
data.Wdi = 2.1168; units.Wdi = 'g'; label.Wdi = 'ultimate dry weight'; bibkey.Wdi = {};
  comment.Wdi = 'For aposymbiotic colonies only. Holcomb et al. 2012';
data.Wdim = 2.0964; units.Wdim = 'g'; label.Wdim = 'ultimate dry weight for males'; bibkey.Wdim = {};
  comment.Wdim = 'For aposymbiotic colonies only. Holcomb et al. 2012';

data.tR = 365; units.tR = 'd'; label.tR = 'time since birth at first egg production'; bibkey.tR = {};
  temp.tR = C2K(22); units.temp.tR = 'K'; label.temp.tR = 'temperature';
  comment.tR = 'For aposymbiotic colonies only. Estimated.';

data.Wwi = 0.005; units.Wwi = 'g'; label.Wwi = 'ultimate wet weight'; bibkey.Wwi = {};
  comment.Wwi = 'For aposymbiotic colonies only. Estimated.';

data.ah = 30; units.ah = 'd'; label.ah = 'age at hatch'; bibkey.ah = {};
  temp.ah = C2K(22); units.temp.ah = 'K'; label.temp.ah = 'temperature';
  comment.ah = 'For aposymbiotic colonies only. Estimated. Hatch=metamorphosis';

data.Ri = 547.94; units.Ri = '#/d'; label.Ri = 'ultimate reproduction rate'; bibkey.Ri = {};
  temp.Ri = C2K(22); units.temp.Ri = 'K'; label.temp.Ri = 'temperature';
  comment.Ri = 'For aposymbiotic colonies only. Estimated on a per-polyp by J. McAlister on the basis of 5,000 per year * 40 polyps in the average colony, divided by 365.';

%% set weights for all real data
weights = setweights(data, []);

%% set pseudodata and respective weights
[data, units, label, weights] = addpseudodata(data, units, label, weights);

%% pack auxData and txtData for output
auxData.temp = temp;
txtData.units = units;
txtData.label = label;
txtData.bibkey = bibkey;
txtData.comment = comment;

%% Discussion points
D1  = 'AmP for aposymboitic colonies ONLY.';
metaData.bibkey.D1 = 'D1';
metaData.discussion = struct('D1',D1);

%% Links
metaData.links.id_CoL = 'J3HK'; % Cat of Life
metaData.links.id_EoL = '45276015'; % Ency of Life
metaData.links.id_Wiki = 'Astrangia_poculata'; % Wikipedia
metaData.links.id_ADW = 'Astrangia_poculata'; % Anim Div. Web
metaData.links.id_Taxo = '12006'; % Taxonomicon
metaData.links.id_WoRMS = '157967';

%% References
bibkey = 'Article'; type = 'article'; bib = [ ...
'author = {M. Holcomb, A. L. Cohen, and D. C. McCorkle}, ' ... 
'title = {An investigation of the calcification response of the scleractinian coral Astrangia poculata to elevated pCO2 and the effects of nutrients, zooxanthellae and gender}, ' ... 
'journal = {Biogeosciences}, ' ... 
'year = {2012}, ' ... 
'volume = {9}, ' ... 
'pages = {29-39}, ' ... 
'doi = {doi:10.5194/bg-9-29-2012}, ' ... 
'howpublished = {\url{https://bg.copernicus.org/articles/9/29/2012/}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'Kooy2010'; type = 'Book'; bib = [ ...  % used in setting of chemical parameters and pseudodata
'author = {Kooijman, S.A.L.M.}, ' ...
'year = {2010}, ' ...
'title  = {Dynamic Energy Budget theory for metabolic organisation}, ' ...
'publisher = {Cambridge Univ. Press, Cambridge}, ' ...
'pages = {Table 4.2 (page 150), 8.1 (page 300)}, ' ...
'howpublished = {\url{http://www.bio.vu.nl/thb/research/bib/Kooy2010.html}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'Wiki'; type = 'misc'; bib = [ ...
'howpublished = {\url{https://en.wikipedia.org/wiki/Astrangia_poculata}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
